formatter: "markdown table"
version: "0.16"
recursive:
  enabled: false
  path: ""
sections:
  hide: []
  show: []
content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: readme.md
  mode: inject
template: |-
  <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
  {{ .Content }}
  <!-- END_AUTOMATED_TF_DOCS_BLOCK -->
output-values:
  enabled: false
  from: ""
sort:
  enabled: true
  by: name
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true